apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/app-sre/container-images?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "10"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "master" && files.all.exists(x, x.matches('qontract-reconcile-builder/|.tekton/qontract-reconcile-builder-master-pull-request.yaml|.tekton/qontract-reconcile-builder-master-push.yaml'))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: container-images-master
    appstudio.openshift.io/component: qontract-reconcile-builder-master
    pipelines.appstudio.openshift.io/type: build
  name: qontract-reconcile-builder-master-on-pull-request
  namespace: app-sre-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/app-sre-tenant/container-images-master/qontract-reconcile-builder-master:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: qontract-reconcile-builder/Dockerfile
  - name: path-context
    value: qontract-reconcile-builder/
  pipelineRef:
    params:
    - name: url
      value: https://github.com/app-sre/shared-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/multi-arch-build-pipeline.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-qontract-reconcile-builder-master
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
